version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-backend
    environment:
      - PORT=3000
      - WATCHPACK_POLLING=true
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src
      - ./backend/upload-images:/app/upload-images

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: next-frontend
    environment:
      - PORT=4000
      - WATCHPACK_POLLING=true
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - ./frontend:/app

  feedbacker-adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8060:8060"
    logging:
      driver: "none"